// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/category': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/category/index.get').default>>>>
    }
    '/api/filterRecipes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/filterRecipes.get').default>>>>
    }
    '/api/measures': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/measures/index.get').default>>>>
    }
    '/api/recipe/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recipe/[id].get').default>>>>
    }
    '/api/recipe': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recipe/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/recipe/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}